// <auto-generated />
namespace AppPrincipale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajoutNAS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajoutNAS));
        
        string IMigrationMetadata.Id
        {
            get { return "201611292031011_ajoutNAS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
